spring:
   datasource:
      username: educationhub
      password: educationhub
      url: jdbc:mysql://localhost:3306/educationhub
      
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
      defer-datasource-initialization: true
   
   sql:
      init:
         mode: never
         
         # it is our configuration file to create connection with database using spring datasource , create and populate tables using spring jpa and execuse query using spring sql